source 'https://rubygems.org'

gem 'sinatra'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'pg'
gem 'json'

group :development, :test do
  gem 'pry'
  gem 'rerun'
end

group :test do
  gem 'minitest'
end
